name: jedi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # 下拉刷新、上拉加载更多
  # https://pub.dartlang.org/packages/pulltorefresh_flutter
  # pulltorefresh_flutter: "^0.1.9"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # 要向应用程序添加资产，请添加资产部分，如下所示：
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/navigation_home.png
    - assets/navigation_home_selected.png
    - assets/navigation_classify.png
    - assets/navigation_classify_selected.png
    - assets/navigation_society.png
    - assets/navigation_society_selected.png
    - assets/navigation_earnings.png
    - assets/navigation_earnings_selected.png
    - assets/navigation_my.png
    - assets/navigation_my_selected.png
    - assets/app_bar_more.png
    - assets/app_bar_service.png
    - assets/app_bar_scan.png
    - assets/app_bar_service_angle.png
    - assets/featured_99_shipping.png
    - assets/geatured_taobao_grab.png
    - assets/featured_newcomers_yes.png
    - assets/featured_poly_offer.png
    - assets/featured_today_recommended.png
    - assets/featured_tmall_supermarket.png
    - assets/featured_tmall_international.png
    - assets/featured_today_explosion.png
    - assets/featured_peanuts_selection.png
    - assets/featured_large_amount.png
    - assets/app_bar_plate_1.png
    - assets/app_bar_plate_2.png
    - assets/app_bar_plate_3.png
    - assets/featured_headlines_title.png
    - assets/home_porcelain_backplane_1.png
    - assets/home_porcelain_backplane_2.png
    - assets/home_porcelain_backplane_3.png
    - assets/home_porcelain_backplane_4.png
    - assets/home_porcelain_backplane_5.png
    - assets/hot_list_sign.png
    - assets/home_roll_backplane.png
    - assets/recommend_you_title.png
    - assets/recommended_volume.png
    - assets/app_bar_scan_gray.png
    - assets/app_bar_service_gray.png
    - assets/community_title.png
    - assets/community_sharing.png
    - assets/community_label.png
    - assets/income_bottom_plate.png
    - assets/refresh.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: PingFangRegular
      fonts:
        - asset: fonts/苹方黑体-准-简.ttf
    - family: PingFangMedium
      fonts:
        - asset: fonts/苹方黑体-中黑-简.ttf
    - family: PingFangBold
      fonts:
        - asset: fonts/苹方黑体-中粗-简.ttf
